name: 'Terraform'
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.ROLE_NAME }}
            aws-region: ${{ secrets.AWS_REGION }}
            
      - name: Terraform Init
        run: terraform init
      - name: Select Workspace
        run: terraform workspace select ${{ github.event.inputs.workspace }}
      - name: Terraform Plan
        run: terraform plan -var-file="${{ github.event.inputs.workspace }}.tfvars"
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -var-file="${{ github.event.inputs.workspace }}.tfvars" -auto-approve
 
